apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gpu-metric-scheduler
  name: gpu-metric-scheduler
spec:
  selector:
    matchLabels:
      app: gpu-metric-scheduler
  template:
    metadata:
      labels:
        app: gpu-metric-scheduler
      name: gpu-metric-scheduler
    spec:
      nodeName: master
      serviceAccountName: gpu-metric-scheduler
      containers:
        - name: gpu-metric-scheduler
          image: ketidevit/gpu-metric-scheduler:v1.0
        - name: kubectl
          image: kelseyhightower/kubectl:1.3.4
          args:
            - "proxy"
