kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gpu-metric-scheduler
  namespace: default
subjects:
- kind: ServiceAccount
  name: gpu-metric-scheduler
  namespace: scheduler
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
